# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    # -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.1
    hooks:
    -   id: rst-backticks
#-   repo: https://github.com/timothycrosley/isort
#    rev: 4.3.21-2
#    hooks:
#    -   id: isort
-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: check-poetry
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.720
#    hooks:
#    -   id: mypy
#        args: [--html-report .mypy_cache src/cltkv1]

default_language_version:
    python: python3
